name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: dastraus007/notes-app-frontend:latest

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: dastraus007/notes-app-backend:latest

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Copy docker‑compose.yml to server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml
          target: /home/${{ secrets.SERVER_USER }}/notes-app/

      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd notes-app
            docker-compose pull
            docker-compose down
            docker-compose up -d --remove-orphans
