name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install & lint ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: |
        npm ci
        npm run lint

    - name: Test ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: npm test
